import type { FieldName } from './types'

// Alias lists used for automatic column-mapping detection. Each list includes
// common spellings/casings analysts export from their own systems, plus the
// headers used by the Kaggle-style Amazon product export (product_id,
// discounted_price, actual_price, about_product, review_content, img_link,
// product_link, rating_count) as generic aliases — not an Amazon-specific
// code path, so any file using similar column names benefits.

export const FIELD_ALIASES: Record<FieldName, string[]> = {
  // Shared / sales
  orderId: ['order id', 'order_id', 'order number', 'order_number', 'order no', 'order_no'],
  orderDate: [
    'order date',
    'order_date',
    'date',
    'purchase date',
    'purchase_date',
    'order timestamp',
    'order_timestamp',
  ],
  sku: [
    'product id',
    'product_id',
    'sku',
    'product sku',
    'product_sku',
    'asin',
    'item id',
    'item_id',
    'item sku',
    'product code',
    'product_code',
  ],
  quantity: ['quantity', 'qty', 'units', 'unit count', 'unit_count', 'quantity ordered', 'quantity_ordered'],
  sellingPrice: [
    'selling price',
    'selling_price',
    'unit price',
    'unit_price',
    'price',
    'sale price',
    'sale_price',
    'item price',
    'item_price',
  ],
  orderStatus: ['order status', 'order_status', 'status'],
  discount: [
    'discount',
    'discount amount',
    'discount_amount',
    'discount percentage',
    'discount_percentage',
    'discount pct',
    'discount_pct',
  ],
  currency: ['currency', 'currency code', 'currency_code'],

  // Products
  productName: ['product name', 'product_name', 'name', 'title', 'item name', 'item_name'],
  category: ['category', 'product category', 'product_category', 'category name', 'categories'],
  brand: ['brand', 'manufacturer', 'vendor'],
  currentPrice: [
    'current price',
    'current_price',
    'discounted price',
    'discounted_price',
    'list price',
    'list_price',
  ],
  originalPrice: [
    'original price',
    'original_price',
    'actual price',
    'actual_price',
    'msrp',
    'regular price',
    'regular_price',
  ],
  productCost: ['product cost', 'product_cost', 'cost', 'unit cost', 'unit_cost', 'cogs'],
  rating: ['rating', 'avg rating', 'average rating', 'average_rating', 'star rating', 'stars'],
  ratingCount: [
    'rating count',
    'rating_count',
    'number of ratings',
    'num ratings',
    'num_ratings',
    'review count',
    'review_count',
  ],
  description: ['description', 'about product', 'about_product', 'product description', 'product_description', 'details'],
  reviewText: ['review text', 'review_text', 'review content', 'review_content', 'reviews', 'review body', 'review_body'],
  productUrl: ['product url', 'product_url', 'url', 'link', 'product link', 'product_link'],
  imageUrl: ['image url', 'image_url', 'img link', 'img_link', 'image', 'thumbnail', 'thumbnail url', 'thumbnail_url'],

  // Inventory
  availableInventory: [
    'available inventory',
    'available_inventory',
    'inventory',
    'available quantity',
    'available_quantity',
    'stock',
    'available stock',
    'available_stock',
    'quantity available',
    'quantity_available',
  ],
  reservedInventory: [
    'reserved inventory',
    'reserved_inventory',
    'reserved quantity',
    'reserved_quantity',
    'reserved',
    'allocated',
  ],
  warehouse: ['warehouse', 'warehouse name', 'warehouse_name', 'location', 'fulfillment center', 'fulfillment_center'],
  incomingInventory: [
    'incoming inventory',
    'incoming_inventory',
    'incoming quantity',
    'incoming_quantity',
    'inbound',
    'inbound inventory',
    'inbound_inventory',
    'on order',
    'on_order',
  ],
  reorderLevel: [
    'reorder level',
    'reorder_level',
    'reorder point',
    'reorder_point',
    'restock level',
    'restock_level',
    'safety stock',
    'safety_stock',
  ],
}
